rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category-list', views.CategoryListView.as_view(), name='category-list'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('addproduct/', views.ProductAddView.as_view(), name='product-add'),
    path('productlist/', views.ProductListView.as_view(), name='product-list'),
    path('page-detail/<slug:pk>', views.PageDetailView.as_view(), name='page-detail'),
    path('productdetail/<slug:pk>', views.ProductDetailView.as_view(), name='product-detail'),
    path('likeproduct/<slug:pk>', views.LikeProduct.as_view(), name='product-like'),
    path('likepage/<slug:pk>', views.LikePage.as_view(), name='page-like'),
    path('trending/', views.TrendingView.as_view(), name='trending'),
    path('discovery/', views.DiscoveryView.as_view(), name='discovery'),
    path('bakers/', views.BakersView.as_view(), name='bakers')
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    # 3 - The above maps any URLs starting with rango/ to be handled by rango.
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    NAME_MAX_LENGTH = 128

    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username


class Product(models.Model):
    SIZE_CHOICES = (
        ('Small', 'Small'),
        ('Middle', 'Middle'),
        ('Big', 'Big')
    )

    TYPE_CHOICES = (
        ('Beans', 'Beans'),
        ('Milk', 'Milk')
    )

    SWEETNESS_CHOICES = (
        ('100%', '100%'),
        ('70%', '70%'),
        ('30%', '30%')

    )

    name = models.CharField(max_length=255)
    size = models.CharField(max_length=10, choices=SIZE_CHOICES)
    type = models.CharField(max_length=255, choices=TYPE_CHOICES)
    sweetness = models.CharField(max_length=10, choices=SWEETNESS_CHOICES)
    img = models.ImageField(upload_to='products')
    location = models.TextField()

    def get_absolute_url(self):
        return reverse('rango:product-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class FavoritePage(models.Model):
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class FavoriteProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return self.user

rango/forms.py
from django import forms
from rango.models import Page, Category, Product
from django.contrib.auth.models import User
from rango.models import UserProfile
from crispy_forms.helper import FormHelper


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class FilterForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(FilterForm, self).__init__(*args, **kwargs)
        helper = FormHelper()
        helper.form_class = 'form-horizontal'
        helper.label_class = 'col-lg-2'
        helper.field_class = 'col-lg-8'
        self.helper = helper
        self.fields['size'].required = False
        self.fields['type'].required = False
        self.fields['sweetness'].required = False

    class Meta:
        model = Product
        fields = ('size', 'type', 'sweetness')

rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views import View
from django.views.generic import ListView, TemplateView, CreateView, DetailView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin

from rango.models import Category, Page, Product, FavoriteProduct, FavoritePage
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm, ProductForm, FilterForm
from datetime import datetime


def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list
    
    # response = render(request, 'rango/index.html', context=context_dict)
    # visitor_cookie_handler(request, response)
    # return response
    
    #request.session.set_test_cookie() 
    visitor_cookie_handler(request)

    return render(request, 'rango/home.html', context=context_dict)


def about(request):

    #  if request.session.test_cookie_worked():
    #  print("Test cookies worked!")
    #  request.session.delete_test_cookie()
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/about.html', context=context_dict)

def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)

        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None
    
    return render(request, 'rango/category.html', context=context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('rango:index'))
        else:
            print(form.errors)
    
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        category = None
    
    if category is None:
        return redirect(reverse('rango:index'))

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)  # This could be better done; for the purposes of TwD, this is fine. DM.
    
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    
    return render(request, 'rango/register.html', 
               context={'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango/login.html')

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    
    request.session['visits'] = visits


class CategoryListView(ListView):
    queryset = Category.objects.all()
    template_name = 'rango/category-list.html'


class Profile(TemplateView):
    template_name = 'rango/profile.html'


class ProductAddView(LoginRequiredMixin, CreateView):
    model = Product
    form = ProductForm
    template_name = 'rango/product-add.html'
    fields = '__all__'


class ProductListView(FormMixin, ListView):
    model = Product
    template_name = 'rango/product-list.html'
    form_class = FilterForm

    def get_queryset(self):
        queryset = super(ProductListView, self).get_queryset()
        form = self.get_form()
        if form.is_valid():
            data = form.cleaned_data
            data = {k: v for k, v in data.items() if v}
            queryset = queryset.filter(**data)

        q = self.request.GET.get('q')
        if q is not None:
            queryset = queryset.filter(name__icontains=q)

        return queryset

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        form = self.get_form()

        context['form'] = form
        return context

    def get_form_kwargs(self):
        """Return the keyword arguments for instantiating the form."""
        kwargs = {
            'initial': self.get_initial(),
            'prefix': self.get_prefix(),
        }

        kwargs.update({
            'data': self.request.GET,
        })
        return kwargs


class PageDetailView(DetailView):
    model = Page
    template_name = 'rango/page-detail.html'


class ProductDetailView(DetailView):
    model = Product
    template_name = 'rango/product-detail.html'


class LikeProduct(LoginRequiredMixin, SingleObjectMixin, View):
    model = Product

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        FavoriteProduct.objects.create(product=obj, user=request.user)
        return redirect('rango:product-detail', pk=obj.pk)


class LikePage(LoginRequiredMixin, SingleObjectMixin, View):
    model = Page

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        FavoritePage.objects.create(page=obj, user=request.user)
        return redirect('/')


class TrendingView(TemplateView):
    template_name = 'rango/trending.html'


class DiscoveryView(TemplateView):
    template_name = 'rango/discovery.html'


class BakersView(TemplateView):
    template_name = 'rango/bakers.html'

templates/rango/about.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    About us
{% endblock %}

{% block content %}
<h1 style="text-align: center;margin-bottom: 30px">About Us</h1>
<div class="row" style="display: flex;justify-content: center;margin: 0">
<img src="/media/v2_qxf1d8.png" alt="" class="col-md-12">
</div>

<p style="font-size: 18px;margin-top: 30px">
Team Fireworks is a group of programmers who really love cooking. Sweets are our favorite thing, because we consume a lot of energy when we work and study. Therefore, we need to eat a lot of delicious food to supplement the food. But as we know, there are too few delicious sweets on the market. We set up this website to collect all kinds of desserts, so that everyone knows that mousse is not only made in one way. We believe that food can be relaxing, and we hope everyone enjoys desserts.
</p>
<p style="margin-top: 30px">
Phone: 8792983 <br>
Email: DD_Fireworks@gmail.combr> <br>
Address: 180 Lambeth Rd, London SE1 7JY, United Kingdombr>
</p>
{% endblock %}

templates/rango/bakers.html
{% extends 'base.html' %}

{% block title %}
Bakers
{% endblock %}

{% block page_title %}
Bakers
{% endblock %}

{% block content %}
<h2 style="text-align: center">Most popular bakers/cooks</h2>
<div class="row" style="padding: 20px;background-color: white;margin: 20px 0">
    <div class="col-md-4">
        <img src="/media/b1.png" alt="" style="width: 100%;height: 150px">
    </div>
    <div class="col-md-8">
        <p>
            A chef is a person whose profession is cooking and cooking dishes is the main job content. The profession of chefs appeared very early. About in the slave society, there were already full-time chefs. With the continuous improvement of social material civilization, the profession of chefs has also continued to develop, and the team of full-time chefs has continued to expand.
        </p>
    </div>
</div>

<div class="row" style="padding: 20px;background-color: white;margin: 20px 0">
<div class="col-md-4">
    <img src="/media/b2.png" alt="" style="width: 100%;height: 150px">
</div>
<div class="col-md-8">
    <p>
        A chef is a person whose profession is cooking and cooking dishes is the main job content. The profession of chefs appeared very early. About in the slave society, there were already full-time chefs. With the continuous improvement of social material civilization, the profession of chefs has also continued to develop, and the team of full-time chefs has continued to expand.
    </p>
</div>
</div>

<div class="row" style="padding: 20px;background-color: white;margin: 20px 0">
<div class="col-md-4">
<img src="/media/b3.png" alt="" style="width: 100%;height: 150px">
</div>
<div class="col-md-8">
<p>
    A chef is a person whose profession is cooking and cooking dishes is the main job content. The profession of chefs appeared very early. About in the slave society, there were already full-time chefs. With the continuous improvement of social material civilization, the profession of chefs has also continued to develop, and the team of full-time chefs has continued to expand.
</p>
</div>
</div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            Rango - 
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
        {% block body_block %}
        {% endblock %}
        </div>
        <div> 
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                    <li><a href="{% url 'rango:logout' %}">Logout</a></li>
                    <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                {% else %}
                    <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                    <li><a href="{% url 'rango:login' %}">Login</a></li>
                {% endif %}
                    <li><a href="{% url 'rango:about' %}">About</a></li>
                    <li><a href="{% url 'rango:index' %}">Index</a></li>
                </ul>
        </div>
    </body>
</html>

templates/rango/categories.html
<ul>
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
            <li><strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong></li>
            {% else %}
            <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
   </ul>

templates/rango/category-list.html
{% extends 'base.html' %}

{% block title %}
Categories
{% endblock %}

{% block page_title %}
Categories
{% endblock %}

{% block content %}

{#{% if request.user.is_authenticated %}#}
{#    <a href="{% url 'rango:add_category' %}" class="btn btn-primary">Add Category</a>#}
{#{% endif %}#}
<div style="margin-top: 20px">
{#{% for i in object_list %}#}
{#    <a href="{% url 'rango:show_category' i.slug %}" style="font-size: 20px">{{ i.name }}</a> <br>#}
{#    <hr>#}
{#{% endfor %}#}
<h2 style="text-align: center">BROWSE VARIOUS DESSERTS</h2>
<hr style="margin: 40px 0">
<p style="text-align: center">Find your favorite among the many desserts! Just like the prince finds Cinderella!</p>
</div>

<div style="margin-top: 40px">
    <h4>FEATURED DESERTS</h4>
    <p style="margin-left: 150px">
        The most popular dessert nowadays. Very tasty for this spring.
    </p>
</div>
<div class="row" style="display: flex;justify-content: center">
    <div style="background-color: #F9E3C8;height: 500px" class="col-md-10">
        <h4 style="margin-top: 20px;text-align: center">EXPLORE HUNDREDS OF DESSERT RECIPES</h4>
        <br>
        <p style="text-align: center">Find your new favorite  dessert in our amazing collection of easy recipes.</p>
        <div class="row" style="margin-left: 5px;margin-bottom: 20px">
        You can add category
        <a class="" href="{% url 'rango:add_category' %}">
            &nbsp;here
        </a>.
        </div>
        <div>
            {% for i in object_list %}
                <a href="{% url 'rango:show_category' i.slug %}" style="font-size: 16px">{{ i.name }}</a> <br>
                <hr>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/rango/category.html
{% extends 'base.html' %}
{% load static %}
{% load rango_template_tags %}

{% block header %}
    <style>
    .form-group{
        margin-right: 10px;
    }
    .row{
        margin-left: 0;
    }
    </style>
{% endblock %}

{% block page_title %}

{% endblock %}

{% block content %}
    <h1 style="text-align: center">{% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}</h1>
    {% if category %}
    {% if user.is_authenticated %}
    <div class="row">
    You can add page
    <a class="" href="{% url 'rango:add_page' category.slug %}">
        &nbsp;here
    </a>.
    </div>
    {% endif %}
    {% if pages %}
    <ul style="margin-top: 20px">
        {% for page in pages %}
            <li style="display: flex;justify-content: space-between"><a href="{{ page.url }}" style="font-size: 20px" class="btn-link">{{ page.title }}</a>
                {% if not page|is_like_page:request.user %}<a href="{% url 'rango:page-like' page.pk %}">Like</a>{% endif %}
            </li>
            <hr>
        {% endfor %}
    </ul>
    {% else %}
    <strong>No pages currently in category.</strong>
    {% endif %}


    {% else %}
    The specified category does not exist.
    {% endif %}
{% endblock %}

templates/rango/discovery.html
{% extends 'base.html' %}

{% block title %}
Discovery
{% endblock %}

{% block page_title %}
Discovery
{% endblock %}

{% block content %}
<h2 style="text-align: center">Want to find something different?</h2>
<div class="row" style="padding: 20px;background-color: white;margin: 20px 0">
    <div class="col-md-4">
        <img src="/media/d1.jpg" alt="" style="width: 100%;height: 150px">
    </div>
    <div class="col-md-8">
        <p>
            Here i have some recommendations.
In the broad sense of Asian culture, chocolate and chewing gum are often regarded as a kind of candy. In European and American countries, candy refers only to products made with white sugar or maltose. In ancient times, Europe and the United States even used honey as a raw material to make candies, but it was not suitable for industrial production because of the excessive amount of honey that was difficult to control.
        </p>
    </div>
</div>

<div class="row" style="padding: 20px;background-color: white;margin: 20px 0">
<div class="col-md-4">
    <img src="/media/d2.png" alt="" style="width: 100%;height: 150px">
</div>
<div class="col-md-8">
    <p>
        Here i have some recommendations.
In the broad sense of Asian culture, chocolate and chewing gum are often regarded as a kind of candy. In European and American countries, candy refers only to products made with white sugar or maltose. In ancient times, Europe and the United States even used honey as a raw material to make candies, but it was not suitable for industrial production because of the excessive amount of honey that was difficult to control.
    </p>
</div>
</div>

<div class="row" style="padding: 20px;background-color: white;margin: 20px 0">
<div class="col-md-4">
<img src="/media/d3.png" alt="" style="width: 100%;height: 150px">
</div>
<div class="col-md-8">
<p>
    Here i have some recommendations.
In the broad sense of Asian culture, chocolate and chewing gum are often regarded as a kind of candy. In European and American countries, candy refers only to products made with white sugar or maltose. In ancient times, Europe and the United States even used honey as a raw material to make candies, but it was not suitable for industrial production because of the excessive amount of honey that was difficult to control.
</p>
</div>
</div>
{% endblock %}

templates/rango/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block page_title %}

{% endblock %}

{% block content %}
<div class="row">
    <h1 style="text-align: center" class="col-md-12">Dessert Desire</h1>
</div>
<div class="row" style="margin-top: 10px">
    <p class="col-md-12" style="text-align: center">Satisfy all your desires for desserts, physically, psychologically...</p>
</div>
<div style="height: 500px;background-image: url('/media/home.jpg');background-repeat: no-repeat;width: 100%;-webkit-background-size: 100% 500px;">
    <div class="row" style="display: flex;justify-content: center;">
        <div style="background-color: rgba(255,255,255,0.8);;height: 300px;margin-top: 100px" class="col-md-6">
            <h3 style="text-align: center;color: #F2757C;margin-top: 30px">Hello, strawberry!</h3>
            <p style="font-size: 18px;text-align: center;color: black">Explore the hottest strawberry <br>desserts in March</p>
            <p style="text-align: center">March 7, 2021</p>
            <div class="row" style="display: flex;justify-content: center;margin-top: 30px">
                <button class="btn btn-outline-secondary">Read More</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/rango/page-detail.html
{% extends 'base.html' %}

{% block title %}
Page Detail
{% endblock %}

{% block page_title %}
Page Detail
{% endblock %}

{% block content %}
    <h2>{{ object.title }}</h2>
    <p>Category: {{ object.category }}</p>
    <p>url: <a href="{{ object.url }}">{{ object.url }}</a></p>
{% endblock %}

templates/rango/product-add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Add Product
{% endblock %}

{% block page_title %}
Add Product
{% endblock %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
{{ form|crispy }}
<button class="btn btn-primary" type="submit">Add</button>
</form>
{% endblock %}

templates/rango/product-detail.html
{% extends 'base.html' %}
{% load rango_template_tags %}

{% block title %}
{{ object.name }}
{% endblock %}

{% block content %}
<div class="row">
</div>
<div style="margin-top: 20px">
    <img src="/media/{{ object.img }}" alt="" style="width: 300px;height: 300px">
</div>
<div>
    <div>
        <br>
        <h3>Name: {{ object.name }}</h3>
        Sweetness: {{ object.sweetness }} <br>
        Type: {{ object.type }} <br>
        Size: {{ object.size }} <br>
    </div>
    <hr>
    <div>
        Location: {{ object.location }}
    </div>
    <hr>

    <div>
        <a class="btn btn-success {% if object|is_like_product:request.user %}disabled{% endif %}"  href="{% url 'rango:product-like' object.pk %}">Like Product</a>
    </div>

</div>
{% endblock %}

templates/rango/product-list.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

{% block header %}
    <style>
    .form-group{
        margin-right: 10px;
    }
    .row{
        margin-left: 0;
    }
    </style>
{% endblock %}

{% block title %}
Products
{% endblock %}

{% block page_title %}
Products
{% endblock %}

{% block content %}
    <form action="" method="get" class="row" style="margin-left: 0;display: flex;justify-content: center">
        <input type="text" class="form-control col-md-6" name="q" value="{{ request.GET.q }}" style="margin-right: 10px">
        <button class="btn btn-secondary" type="submit" style="background-color: #F4E8D7;color: black">Search</button>
    </form>
    <div class="row" style="margin-top: 20px">
        <form action="" method="get" class="form-inline">
            {{ form|crispy }}
             <button class="btn btn-secondary" type="submit" style="margin-left: 20px;background-color: #F4E8D7;color: black">Filter</button>
        </form>
    </div>

    {% if request.user.is_authenticated %}
    <br>
    <div class="row">
        You can add product
        <a class="" href="{% url 'rango:product-add' %}">
            &nbsp;here
        </a>.
    </div>
    {% endif %}

  <div class="row row-cols-4" style="margin-top: 20px">
  {% for product in object_list %}
    <div class="col" style="background-color: #F5F5F5;padding: 0;margin: 0 5px" onclick="window.location.href='{% url 'rango:product-detail' product.pk %}'">
        <img src="/media/{{ product.img }}" alt="" style="width: 100%;height: 250px">
        <div style="padding: 10px">
            <h2>{{ product.name }}</h2>
            <span class="badge badge-primary">{{ product.size }}</span>
            <span class="badge badge-success">{{ product.type }}</span>
            <span class="badge badge-warning">{{ product.sweetness }}</span>
        </div>
    </div>
  {% endfor %}
  </div>
{% endblock %}

templates/rango/register.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Register
{% endblock %}

{% block page_title %}
Register
{% endblock %}

{% block content %}
<h1>Register for Rango</h1>
{% if registered %}
Rango says: <strong>thank you for registering!</strong>
<a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
{% else %}
Rango says: <strong>register here!</strong><br />
<form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
   
    {% csrf_token %}
    {{ user_form|crispy }}
    {{ profile_form|crispy }}
    <a href="{% url 'rango:login' %}" class="btn-link">Already Have a account?</a>
    <br><br>
    <button type="submit" class="btn btn-primary">Register</button>
</form>
{% endif %}
{% endblock %}