rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category-list', views.CategoryListView.as_view(), name='category-list'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('addproduct/', views.ProductAddView.as_view(), name='product-add'),
    path('productlist/', views.ProductListView.as_view(), name='product-list'),
    path('page-detail/<slug:pk>', views.PageDetailView.as_view(), name='page-detail'),
    path('productdetail/<slug:pk>', views.ProductDetailView.as_view(), name='product-detail'),
    path('likeproduct/<slug:pk>', views.LikeProduct.as_view(), name='product-like'),
    path('likepage/<slug:pk>', views.LikePage.as_view(), name='page-like'),
    path('trending/', views.TrendingView.as_view(), name='trending'),
    path('discovery/', views.DiscoveryView.as_view(), name='discovery'),
    path('bakers/', views.BakersView.as_view(), name='bakers')
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    # 3 - The above maps any URLs starting with rango/ to be handled by rango.
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/nav.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #FBF5EC">
<a class="navbar-brand" href="#" style="color: #575757">Dessert Desire</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarCollapse">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" href="/" style="color: #E1A59C">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'rango:about' %}" tabindex="-1" aria-disabled="true" style="color: #575757">About</a>
    </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'rango:trending' %}" tabindex="-1" aria-disabled="true" style="color: #575757">Trending</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'rango:discovery' %}" tabindex="-1" aria-disabled="true" style="color: #575757">Discovery</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'rango:bakers' %}" tabindex="-1" aria-disabled="true" style="color: #575757">Bakers</a>
      </li>
    <li class="nav-item" >
      <a class="nav-link" href="{% url 'rango:category-list' %}" style="color: #575757">Categories</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'rango:product-list' %}" style="color: #575757">Shops</a>
    </li>

  </ul>
  <div class="mt-2 mt-md-0">

      {% if request.user.is_authenticated %}
          <a href="{% url 'rango:profile' %}" style="color: #575757">{{ request.user.username }}</a><span> / </span><a href="{% url 'rango:logout' %}" style="color: #575757">Logout</a>
      {% else %}
          <a class="btn btn-secondary" href="{% url 'rango:login' %}" style="color: #FBF5EC">Login</a>
      {% endif %}
  </div>
<form class="form-inline mt-2 mt-md-0" style="margin-left: 20px">
    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
  </form>
</div>
</nav>